services:
  - type: web
    name: nakama-server
    env: docker
    dockerfilePath: ./backend/Dockerfile
    dockerContext: ./backend
    plan: free
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: NAKAMA_ENCRYPTION_KEY
        generateValue: true
      - key: NAKAMA_SERVER_KEY
        generateValue: true
      - key: NAKAMA_HTTP_KEY
        generateValue: true
      - key: NAKAMA_SIGNING_KEY
        generateValue: true

      - key: NAKAMA_CONSOLE_PASSWORD
        generateValue: true

databases:
  - name: nakama-postgres
    databaseName: nakama
    user: nakama_user
    plan: free